Dream/urls.py
# coding=utf-8
"""Dreams URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import url, include
from django.contrib import admin
from DreamsApp import views
from DreamsApp.api import urls

urlpatterns = [
    url(r'^$', views.user_login, name='login'),
    url(r'^clients$', views.clients, name='clients'),
    url(r'^clientSave$', views.save_client, name='save_client'),
    url(r'^clientEdit$', views.edit_client, name='edit_client'),
    url(r'^clientDelete$', views.delete_client, name='delete_client'),
    url(r'^client$', views.client_profile),
    url(r'^follow_ups$', views.follow_ups, name='follow_ups'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^ivgetTypes$', views.get_intervention_types),
    url(r'^ivgetType$', views.get_intervention_type),
    url(r'^getExternalOrganisations$', views.get_external_organisation),
    url(r'^getExitReasons', views.get_exit_reasons),
    url(r'^getInterventionTypes$', views.get_all_intervention_types),
    url(r'^getImplementingPartners$', views.get_implementing_partners),
    url(r'^initiateReferral$', views.initiate_referral),
    url(r'^getMinMaxDateOfBirth', views.get_min_max_date_of_birth),
    url(r'^getUnsuccessfulFollowUpAttempts$', views.get_unsuccessful_followup_attempts),
    url(r'^ivSave$', views.save_intervention),
    url(r'^ivList$', views.get_intervention_list),
    url(r'^ivGet$', views.get_intervention),
    url(r'^ivUpdate$', views.update_intervention),
    url(r'^editFollowUp$', views.update_follow_up),
    url(r'^ivDelete$', views.delete_intervention),
    url(r'^deleteFollowUp$', views.delete_follow_up),
    url(r'^intervention$', views.testajax),
    url(r'^getSubCounties$', views.get_sub_counties),
    url(r'^getWards$', views.get_wards),
    url(r'^logout$', views.log_me_out),
    url(r'^reporting$', views.reporting, name='reporting'),
    url(r'^help$', views.user_help, name='user_help'),
    url(r'^help/download/$', views.user_help_download, name='user_help_download'),
    url(r'^logs$', views.logs, name='logs'),
    url(r'^admin/users$', views.users, name='users'),
    url(r'^admin/users/save$', views.save_user, name='new user'),
    url(r'^admin/users/change_cred$', views.change_cred, name='change_cred'),
    url(r'^admin/users/toggle_status$', views.toggle_status, name='toggle_user_status'),
    url(r'^grievances$', views.grievances_list, name='grievances'),
    url(r'^grievances/create$', views.grievances_create, name='grievances_create'),
    url(r'^grievances/edit', views.grievances_edit, name='grievances_edit'),
    url(r'^grievances/delete', views.grievances_delete, name='grievances_delete'),
    url(r'^grievances/get', views.grievances_get, name='grievances_get'),
    url(r'^cashTransfer/save', views.cash_transfer_details_save, name='cash_transfer_details_save'),
    url(r'^download-enrollment-report/$', views.download_raw_enrollment_export),
    url(r'^download-intervention-export/$', views.download_raw_intervention_export),
    url(r'^export-page', views.export_page),
    url(r'^intervention-export-page', views.intervention_export_page),
    url(r'^service-layering-export-page', views.individual_service_layering_export_page),
    url(r'^download-service-layering-report/$', views.download_services_received_export),
    url(r'^client_baseline_info', views.viewBaselineData),
    url(r'^update-demographics', views.update_demographics_data),
    url(r'^update-individual-household', views.update_individual_and_household_data),
    url(r'^update-education-employment', views.update_edu_and_employment_data),
    url(r'^update-hiv-testing', views.update_hiv_testing_data),
    url(r'^update-sexuality', views.update_sexuality_data),
    url(r'^update-reproductive-health', views.update_rep_health_data),
    url(r'^update-gbv', views.update_gbv_data),
    url(r'^update-drug-use', views.update_drug_use_data),
    url(r'^update-programme-participation', views.update_programme_participation_data),
    url(r'^client/exit$', views.exit_client),
    url(r'^client/unexit$', views.unexit_client),
    url(r'^client/transfer$', views.transfer_client, name='transfer_client'),
    url(r'^client-transfers/(?P<transferred_in>[0-1])$', views.client_transfers, name='client_transfers'),
    url(r'^client-referrals/(?P<referred_in>[0-1])$', views.client_referrals, name='client_referrals'),
    url(r'^accept-client-transfer$', views.accept_client_transfer, name='accept_client_transfer'),
    url(r'^reject-client-transfer$', views.reject_client_transfer, name='reject_client_transfer'),
    url(r'^reject-client-referral$', views.reject_client_referral, name='reject_client_referral'),
    url(r'^get-pending-client-transfers-total-count$', views.get_pending_client_transfers_total_count, name='get_pending_client_transfers_total_count'),
    url(r'^get-pending-client-transfers-in-out-count$', views.get_pending_client_transfers_in_out_count,
        name='get_pending_client_transfers_in_out_count'),
    url(r'^get-pending-client-referrals-total-count$', views.get_pending_client_referrals_total_count, name='get_pending_client_referrals_total_count'),
    url(r'^get-pending-client-referrals-in-out-count$', views.get_pending_client_referrals_in_out_count,
        name='get_pending_client_referrals_in_out_count'),
    url(r'^intervention-export-transferred-in-page', views.intervention_export_transferred_in_page,
        name='intervention_export_transferred_in_page'),
    url(r'^download-intervention-transferred-in-report/$', views.download_raw_intervention_transferred_in_export,
        name='download_intervention_transferred_in_report'),
    url(r'^client/void$', views.void_client, name='void_client'),
    url(r'^export-client-transfers/(?P<transferred_in>[0-1])$', views.export_client_transfers,
        name='export_client_transfers'),
    url(r'^export-client-referrals/(?P<referred_in>[0-1])$', views.export_client_referrals,
        name='export_client_referrals'),
    url(r'^download-audit-logs', views.download_audit_logs,
        name='download_audit_logs'),
    url(r'^addFollowUp$', views.add_follow_up),
]

urlpatterns += urls.urlpatterns

handler404 = views.page_not_found
handler400 = views.bad_request
handler403 = views.permission_denied
handler500 = views.server_error

DreamsApp/models.py
from __future__ import unicode_literals

from django.core.exceptions import ValidationError
from django.db import models, DataError
from django.contrib.auth.models import User
from datetime import datetime
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from DreamsApp.constants import *
from django.utils.html import format_html


class MaritalStatus(models.Model):
    code = models.CharField(verbose_name='Marital Status Code', max_length=10, null=False, blank=False)
    name = models.CharField(max_length=100, null=False)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta(object):
        verbose_name = 'Marital Status'
        verbose_name_plural = 'Marital Status'


class County(models.Model):
    code = models.CharField(verbose_name='County Code', max_length=10, default='', null=False, blank=False)
    name = models.CharField(verbose_name='County', max_length=100, default='', null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta(object):
        verbose_name = 'County'
        verbose_name_plural = 'Counties'


class SubCounty(models.Model):
    county = models.ForeignKey(County,on_delete=models.CASCADE, null=True, blank=True)
    code = models.CharField(verbose_name='Sub County Code', max_length=100, default='', null=False, blank=False)
    name = models.CharField(verbose_name='Sub County', max_length=100, default='', null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta(object):
        verbose_name = 'Sub County'
        verbose_name_plural = 'Sub Counties'


class Ward(models.Model):
    sub_county = models.ForeignKey(SubCounty,on_delete=models.CASCADE, null=True, blank=True)
    code = models.CharField(verbose_name='Ward Code', max_length=100, default='', null=False, blank=False)
    name = models.CharField(verbose_name='Ward', max_length=100, default='', null=False, blank=False)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta(object):
        verbose_name = 'Ward'
        verbose_name_plural = 'Wards'


class VerificationDocument(models.Model):
    code = models.IntegerField(name='code', verbose_name='Verification Document Code')
    name = models.CharField(max_length=150, verbose_name='Verification Document Name')

    def __str__(self):
        return '{}'.format(self.name)

    class Meta(object):
        verbose_name = 'Verification Document'
        verbose_name_plural = 'Verification Documents'


class ExternalOrganizationTypeManager(models.Manager):

    def get_by_natural_key(self, name):
        return self.get(name=name)


class ExternalOrganisationType(models.Model):
    objects = ExternalOrganizationTypeManager()

    name = models.CharField(max_length=20, verbose_name='External Organisation Type', null=False, blank=False, unique=True)

    def __str__(self):
        return '{}'.format(self.name)

    def natural_key(self):
        return (self.name, )

    class Meta(object):
        verbose_name = 'External Organisation Type'
        verbose_name_plural = 'External Organisation Types'


class ExternalOrganisation(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False, unique=True, verbose_name='Organisation Name')
    type = models.ForeignKey(ExternalOrganisationType, on_delete=models.PROTECT, null=False, blank=False, verbose_name='Organisation Type')
    code = models.CharField(max_length=20, null=True, blank=True, verbose_name='Organisation Code')
    allow_specific = models.BooleanField(null=False, blank=False, default=False)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta(object):
        verbose_name = 'External Organisation'
        verbose_name_plural = 'External Organisations'


class ImplementingPartnerFunderManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class ImplementingPartnerFunder(models.Model):
    objects = ImplementingPartnerFunderManager()
    name = models.CharField(max_length=20, verbose_name='Funder', null=False, blank=False, unique=True)

    def __str__(self):
        return '{}'.format(self.name)

    def natural_key(self):
        return (self.name, )

    class Meta(object):
        verbose_name = 'Funder'
        verbose_name_plural = 'Funders'


# Give initial default value for service_provider_type
class ImplementingPartner(models.Model):
    code = models.IntegerField(name='code', verbose_name='Implementing Partner Code')
    name = models.CharField(max_length=150, verbose_name='Implementing Partner Name', db_index=True)
    parent_implementing_partner = models.ForeignKey('self', on_delete=models.PROTECT, null=True, blank=True, unique=False, verbose_name='Parent Implementing Partner')
    implementing_partner_funder = models.ForeignKey(ImplementingPartnerFunder, on_delete=models.PROTECT, null=True, blank=True, verbose_name='Funder')

    def __str__(self):
        return '{}'.format(self.name)

    class Meta(object):
        verbose_name = 'Implementing Partner'
        verbose_name_plural = 'Implementing Partners'


class ImplementingPartnerUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    implementing_partner = models.ForeignKey(ImplementingPartner,on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)

    class Meta(object):
        verbose_name = 'Implementing Partner User'
        verbose_name_plural = 'Implementing Partner Users'


#### do we have predefined reasons??
class ExitReason(models.Model):
    code = models.IntegerField(null=False, blank=False, unique=True,
                               validators=[
                                   MaxValueValidator(100),
                                   MinValueValidator(0)
                               ],
                               )
    name = models.CharField(blank=False, null=False, max_length=100, unique=True)

    def __str__(self):
        return '{}'.format(self.name)

    class Meta(object):
        verbose_name = 'Exit Reason'
        verbose_name_plural = 'Exit Reasons'


class Client(models.Model):
    first_name = models.CharField(verbose_name='First Name', max_length=250, null=True, blank=True, db_index=True)
    middle_name = models.CharField(verbose_name='Middle Name', max_length=250, null=True, blank=True, db_index=True)
    last_name = models.CharField(verbose_name='Last Name', max_length=250, null=True, blank=True, db_index=True)
    date_of_birth = models.DateField(verbose_name='Date of Birth', null=True, blank=True, db_index=True)
    is_date_of_birth_estimated = models.NullBooleanField(verbose_name='Date of Birth Estimated', default=False, blank=True)
    verification_document = models.ForeignKey(VerificationDocument,on_delete=models.CASCADE, null=True, blank=True, verbose_name='Verification Document')
    verification_document_other = models.CharField(max_length=250, verbose_name="Verification Document(Other)", blank=True, null=True)
    verification_doc_no = models.CharField(verbose_name='Verification Doc No', max_length=250, null=True, blank=True)
    date_of_enrollment = models.DateField(verbose_name='Date of Enrollment', default=datetime.now, null=True, blank=True, db_index=True)
    age_at_enrollment = models.IntegerField(verbose_name='Age at Enrollment', default=MINIMUM_ENROLMENT_AGE, null=True, blank=True)
    marital_status = models.ForeignKey(MaritalStatus,on_delete=models.CASCADE, verbose_name='Marital Status', null=True, blank=True)
    implementing_partner = models.ForeignKey(ImplementingPartner,on_delete=models.CASCADE, null=True, blank=True, verbose_name='Implementing Partner', db_index=True)
    phone_number = models.CharField(verbose_name='Phone Number', max_length=250, null=True, blank=True)
    dss_id_number = models.CharField(verbose_name='DSS ID Number', max_length=250, null=True, blank=True)
    county_of_residence = models.ForeignKey(County,on_delete=models.CASCADE, verbose_name='County of Residence', null=True, blank=True)
    sub_county = models.ForeignKey(SubCounty,on_delete=models.CASCADE, verbose_name='Sub County', null=True, blank=True)
    ward = models.ForeignKey(Ward,on_delete=models.CASCADE, verbose_name='Ward', null=True, blank=True, db_index=True)
    informal_settlement = models.CharField(verbose_name='Informal Settlement', max_length=250, null=True, blank=True)
    village = models.CharField(verbose_name='Village', max_length=250, null=True, blank=True)
    landmark = models.CharField(verbose_name='Land Mark near Residence', max_length=250, null=True, blank=True)
    dreams_id = models.CharField(verbose_name='DREAMS ID', max_length=250, null=True, blank=True, db_index=True)
    guardian_name = models.CharField(verbose_name='Primary Care Giver/Guardian\' Name', max_length=250, null=True, blank=True)
    relationship_with_guardian = models.CharField(verbose_name='Relationship with Guardian', max_length=250, null=True, blank=True)
    guardian_phone_number = models.CharField(verbose_name='Phone Number(Care giver/Guardian)', max_length=250, null=True, blank=True)
    guardian_national_id = models.CharField(verbose_name='National ID (Care giver/Guardian)', max_length=250, null=True, blank=True)

    enrolled_by = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True)
    odk_enrollment_uuid = models.CharField(max_length=250, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True, db_index=True)
    date_changed = models.DateTimeField(auto_now=True, blank=True, null=True)

    voided = models.BooleanField(default=False, db_index=True)
    reason_voided = models.CharField(blank=True, null=True, max_length=250)
    voided_by = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True, related_name='+')

templates/ajax_response_form/client_drug_use_ajax_form.html
 {% load widget_tweaks %}
<div id="drug_use_replacement">
        <fieldset>
            <div class="form-group form-inline">
                {{ drug_use_form.used_alcohol_last_12months.errors }}
                <label class="control-label enrolment-label">Have you used alcohol in the last 12 months?</label>
                {{ drug_use_form.used_alcohol_last_12months|add_class:"input-sm form-control enrolment-input listen-to-change"|set_data:"show_value:1"|set_data:"show_class:used-alcohol" }}
            </div>
            <div id="frequency_of_alcohol_last_12months" class="form-group form-inline used-alcohol {% if drug_use_form.used_alcohol_last_12months.value != 1 %}hidden{% endif %}">
                {{ drug_use_form.frequency_of_alcohol_last_12months.errors }}
                <label class="control-label enrolment-label">In the past 12 months, how often did you have a drink containing alcohol?</label>
                {{ drug_use_form.frequency_of_alcohol_last_12months|add_class:"input-sm form-control enrolment-input" }}
            </div>
            <div class="form-group form-inline listen-to-change">
                {{ drug_use_form.drug_abuse_last_12months.errors }}
                <label class="control-label enrolment-label">Have you used drugs of abuse or addiction in the last 12 months?</label>
                {{ drug_use_form.drug_abuse_last_12months|add_class:"input-sm form-control enrolment-input listen-to-change"|set_data:"show_value:1"|set_data:"show_class:used-drugs" }}
            </div>
            <div id="drug_used_last_12months" class=" used-drugs {% if drug_use_form.drug_abuse_last_12months.value != 1 %}hidden{% endif %}">
                <div class="form-group form-inline">
                    {{ drug_use_form.drug_used_last_12months.errors }}
                    <label class="control-label enrolment-label">Which types of drugs of abuse/addiction have you used in last 12 months</label>
                    {{ drug_use_form.drug_used_last_12months|add_class:"input-sm form-control enrolment-input" }}
                </div>
                <div class="form-group form-inline used-drugs">
                    {{ drug_use_form.drug_used_last_12months_other.errors }}
                    <label class="control-label enrolment-label">Other</label>
                    {{ drug_use_form.drug_used_last_12months_other|add_class:"input-sm form-control enrolment-input" }}
                </div>
            </div>
            <div class="form-group form-inline">
                {{ drug_use_form.produced_alcohol_last_12months.errors }}
                <label class="control-label enrolment-label">In the last 12 months, have you engaged in brewing or selling alcohol and/or drugs
                    of abuse or addiction</label>
                {{ drug_use_form.produced_alcohol_last_12months|add_class:"input-sm form-control enrolment-input" }}
            </div>
            <div class="form-group">
                {{ drug_use_form.client.as_hidden }}
            </div>
        </fieldset>
    </div>

templates/ajax_response_form/client_hiv_testing_ajax_form.html
{% load widget_tweaks %}
<div id="hiv_testing_replacement">
    <fieldset {% if not perms.DreamsApp.change_client %}disabled{% endif %}>
        <div class="form-group form-inline">
            {{ hiv_form.ever_tested_for_hiv.errors }}
            <label class="control-label enrolment-label">{{ hiv_form.ever_tested_for_hiv.label_tag }}</label>
            {{ hiv_form.ever_tested_for_hiv|add_class:"input-sm form-control enrolment-input listen-to-change"|set_data:"show_value:1"|set_data:"show_class:ever-tested"|set_data:"hide_class:ever-tested-no"|set_data:"hide_on_show:never-tested" }}
        </div>
        <div id="period_last_tested" class="form-group ever-tested form-inline {% if hiv_form.ever_tested_for_hiv.value != 1 %}hidden{% endif %}">
            {{ hiv_form.period_last_tested.errors }}
            <label class="control-label enrolment-label">{{ hiv_form.period_last_tested.label_tag }}</label>
            {{ hiv_form.period_last_tested|add_class:"input-sm form-control enrolment-input listen-to-change"|set_data:"show_value:any"|set_data:"show_class:recent-test" }}
        </div>
        <div id="last_test_result" class="form-group ever-tested-no recent-test form-inline {% if hiv_form.ever_tested_for_hiv.value != 1 %}hidden{% endif %}">
            {{ hiv_form.last_test_result.errors }}
            <label class="control-label enrolment-label">{{ hiv_form.last_test_result.label_tag }}</label>
            {{ hiv_form.last_test_result|add_class:"input-sm form-control enrolment-input listen-to-change"|set_data:"show_value:1"|set_data:"show_class:positive"|set_data:"hide_class:positive enrolled not-in-care not-in-care-other" }}
        </div>
        <div id="enrolled_in_hiv_care" class="form-group ever-tested-no positive form-inline {% if hiv_form.last_test_result.value != 1 %} hidden{% endif %}">
            {{ hiv_form.enrolled_in_hiv_care.errors }}
            <label class="control-label enrolment-label">{{ hiv_form.enrolled_in_hiv_care.label_tag }}</label>
            {{ hiv_form.enrolled_in_hiv_care|add_class:"input-sm form-control enrolment-input listen-to-change"|set_data:"show_value:1"|set_data:"show_class:enrolled"|set_data:"hide_on_show:not-in-care" }}
        </div>
        <div id="care_facility_enrolled" class="form-group ever-tested-no enrolled form-inline {% if hiv_form.enrolled_in_hiv_care.value != 1 %}hidden{% endif %}">
            {{ hiv_form.care_facility_enrolled.errors }}
            <label class="control-label enrolment-label">{{ hiv_form.care_facility_enrolled.label_tag }}</label>
            {{ hiv_form.care_facility_enrolled|add_class:"input-sm form-control enrolment-input" }}
        </div>
        <div id="reason_not_in_hiv_care" class="form-group ever-tested-no not-in-care form-inline {% if hiv_form.enrolled_in_hiv_care.value != 2 %} hidden{% endif %}">
            {{ hiv_form.reason_not_in_hiv_care.errors }}
            <label class="control-label enrolment-label">{{ hiv_form.reason_not_in_hiv_care.label_tag }}</label>
            {{ hiv_form.reason_not_in_hiv_care|add_class:"input-sm form-control enrolment-input listen-to-change"|set_data:"show_value:96"|set_data:"show_class:not-in-care-other" }}
        </div>
        <div id="reason_not_in_hiv_care_other" class="form-group ever-tested-no not-in-care-other form-inline {% if hiv_form.last_test_result.value != 1 %}hidden{% endif %}">
            {{ hiv_form.reason_not_in_hiv_care_other.errors }}
            <label class="control-label enrolment-label">{{ hiv_form.reason_not_in_hiv_care_other.label_tag }}</label>
            {{ hiv_form.reason_not_in_hiv_care_other|add_class:"input-sm form-control enrolment-input" }}
        </div>
        <div id="reason_never_tested_for_hiv" class="form-group ever-tested-no never-tested form-inline {% if hiv_form.ever_tested_for_hiv.value != 2 %}hidden{% endif %}">
            {{ hiv_form.reason_never_tested_for_hiv.errors }}
            <label class="control-label enrolment-label">{{ hiv_form.reason_never_tested_for_hiv.label_tag }}</label>
            {{ hiv_form.reason_never_tested_for_hiv|add_class:"input-sm form-control enrolment-input listen-to-change"|set_data:"show_value:96"|set_data:"show_class:reason-not-tested-other" }}
        </div>
        <div id="reason_never_tested_for_hiv_other" class="form-group ever-tested-no  reason-not-tested-other form-inline {% if hiv_form.reason_never_tested_for_hiv.value != 96 %}hidden{% endif %}">
            {{ hiv_form.reason_never_tested_for_hiv_other.errors }}
            <label class="control-label enrolment-label">{{ hiv_form.reason_never_tested_for_hiv_other.label_tag }}</label>
            {{ hiv_form.reason_never_tested_for_hiv_other|add_class:"input-sm form-control enrolment-input" }}
        </div>
        <div class="form-group form-inline never-tested ever-tested-no {% if hiv_form.ever_tested_for_hiv.value != 2 %}hidden{% endif %}">
            {{ hiv_form.knowledge_of_hiv_test_centres.errors }}
            <label class="control-label enrolment-label">{{ hiv_form.knowledge_of_hiv_test_centres.label_tag }}</label>
            {{ hiv_form.knowledge_of_hiv_test_centres|add_class:"input-sm form-control enrolment-input" }}
        </div>
        <div class="form-group">
            {{ hiv_form.client.as_hidden }}
        </div>
        <div class="form-group form-inline">
             <label class="control-label enrolment-label"></label>
             <button type="submit" class="btn btn-sm btn-primary">Save</button>
        </div>
    </fieldset>
</div>

templates/ajax_response_form/client_programme_participation_ajax_form.html
<div id="program_replacement" >
    <div class="form-group">
        {{ programe_participation_form.dreams_program.errors }}
        <label class="control-label">Which HIV Prevention Programmes have you participated in</label><br/><br/>
        {{ programe_participation_form.dreams_program }}

        {% for p in programe_participation_form.dreams_program.value %}
            {% if p == 96 %}
                <span id="other_program">
            {% else %}
                <span id="other_program" class="hidden">
            {% endif %}

        {{ programe_participation_form.dreams_program_other.errors }}
        <label class="control-label">Other</label>
        {{ programe_participation_form.dreams_program_other }}
        </span>

        {% endfor %}

    </div>
    <div class="form-group">
        {{ programe_participation_form.client.as_hidden }}
    </div>
</div>